TreasureProject/treasure-subgraphs

- subgraphs/bridgeworld-stats/schema.graphql
- Fixes error encountered with the bridgeworld-stats subgraph deployment: https://github.com/TreasureProject/treasure-subgraphs/runs/5171557827?check_suite_focus=true#step:10:82
For some reason this typecheck only comes up on a deploy, not a build :/
> Fix bridgeworld-stats subgraph deploy

- subgraphs/bridgeworld/src/mappings/crafting.ts
- subgraphs/bridgeworld/tests/crafting.test.ts
Previously, we would only record 1 broken treasure, the last one would win. This fix will show multiple in the UI and people won't wonder what happened to their treasures.
> [bridgeworld]: handle multiple broken treasures from crafting

- subgraphs/bridgeworld-stats/schema.graphql
- subgraphs/bridgeworld-stats/src/helpers/constants.ts
- subgraphs/bridgeworld-stats/src/helpers/ids.ts
- subgraphs/bridgeworld-stats/src/helpers/models.ts
- subgraphs/bridgeworld-stats/src/helpers/number.ts
- subgraphs/bridgeworld-stats/src/mappings/atlas-mine.ts
- subgraphs/bridgeworld-stats/src/mappings/legion.ts
- subgraphs/bridgeworld-stats/src/mappings/summoning.ts
- subgraphs/bridgeworld-stats/template.yaml
- subgraphs/bridgeworld-stats/tests/atlas-mine/atlas-mine.test.ts
- subgraphs/bridgeworld-stats/tests/legion/legion.test.ts
- subgraphs/bridgeworld-stats/tests/legion/utils.ts
- subgraphs/bridgeworld-stats/tests/summoning/summoning.test.ts
- subgraphs/bridgeworld-stats/tests/summoning/utils.ts
Closes #35 
Adds summoning stats (with time period filters):
- $MAGIC spent on summons
- Summons started
- Summons finished
- Active summoning wallets
- All summoning wallets
- $MAGIC spent by Legion generation/rarity
- Summons started/finished by Legion generation/rarity
- Summoning results by Legion rarity
Also added a value to track all Atlas Mine wallets (not just the active ones)
> [bridgeworld-stats] add summoning stats

- subgraphs/smolverse/src/helpers/json.ts
Observed error in the subgraph logs:
```
Missing IPFS data at path: https://treasure-marketplace.mypinata.cloud/ipfs/QmeEnvD1QimFbJNigsxwrsfQPw1JuDiFVtBdPAGR3zT5kh/0, data_source: Smol Brains Land, block_hash: 0xd5074f968b1015674d4e32dcc5f1e0850a507827153b7c2c8e28a76ca13c87cb, block_number: 3267140
```
`ipfs.cat` shouldn't be a full URL, just the IPFS hash and path
> [smolverse] fix smol token ipfs.cat call

- subgraphs/smolverse/schema.graphql
- subgraphs/smolverse/src/helpers/metadata.ts
- subgraphs/smolverse/src/mappings/smol-farm.ts
- subgraphs/smolverse/tests/erc721/erc721.test.ts
Adds timestamp to Smol Farm claims
Fixes observed error in subgraph logs:
```
Subgraph instance failed to run: Mapping aborted at ~lib/@graphprotocol/graph-ts/common/value.ts, line 280, column 5, with message: JSON value is not a string. wasm backtrace: 0: 0x2b64 - <unknown>!~lib/string/String#toLowerCase 1: 0x466a - <unknown>!src/mappings/erc721/handleTransfer 2: 0x4dc8 - <unknown>!../../node_modules/@graphprotocol/graph-ts/global/global/id_of_type in handler `handleTransfer` at block #3163503 (e157d799fceb6a140f2186c1333d31d5df611e0c7c7370dbebf10fd633b1b1fb), code: SubgraphSyncingFailure
```
Sorry kind of flying blind here with no metadata on testnet 😁 I think this should do it! Utilizing code from `treasure-marketplace-subgraph` and tested locally with a numeric JSON value.
> [smolverse] fix parsing attributes with numeric values

- subgraphs/bridgeworld/schema.graphql
- subgraphs/bridgeworld/src/mappings/summoning.ts
- subgraphs/bridgeworld/tests/helpers/constants.ts
- subgraphs/bridgeworld/tests/helpers/summoning.ts
- subgraphs/bridgeworld/tests/summoning.test.ts
Closes #50 
- Adds new `resultToken` field to finished `Summon` entities
> [bridgeworld]  Add summoning result to finished summon entity

- subgraphs/smolverse/schema.graphql
- subgraphs/smolverse/src/helpers/metadata.ts
- subgraphs/smolverse/src/helpers/models.ts
- subgraphs/smolverse/src/helpers/number.ts
- subgraphs/smolverse/src/helpers/token-id.ts
- subgraphs/smolverse/src/mappings/common.ts
- subgraphs/smolverse/tests/smol-farm/smol-farm.test.ts
- subgraphs/smolverse/tests/utils.ts
Closes #60 
Changes to support the staked token percentage meter in Smolverse:
- Replaces token ID string tracker with a simple token counter
- Adds staked tokens count
> [smolverse] track collection token and staked token counts

- packages/config/src/arbitrum-testnet.json
- packages/config/src/arbitrum.json
- subgraphs/smolverse/schema.graphql
- subgraphs/smolverse/src/helpers/json.ts
- subgraphs/smolverse/src/helpers/metadata.ts
- subgraphs/smolverse/src/mappings/common.ts
- subgraphs/smolverse/src/mappings/randomizer.ts
- subgraphs/smolverse/src/mappings/smol-brains-school.ts
- subgraphs/smolverse/template.yaml
- subgraphs/smolverse/tests/helpers/metadata.test.ts
- Fixes head size attribute calculation
- Fixes "ABI missing" sync error for `SmolBrains` contract binding
- Updates Randomizer start block so the syncing doesn't start unnecessarily early
- Adds retry mechanism for IPFS fetching
- Adds support for `video` field on `Token` entities to support Smol Brains Land metadata
- Cleans up logs
I deployed the priority items (first two) manually already.
The IPFS retry hasn't gone up yet, so I'm not sure if it will really do anything. I also tried running The Graph's IPFS pinning service on all of the tokenIds, but it didn't seem to do anything either - still getting some IPFS failures during syncing. Not sure how Pinata works, but maybe we can adjust some settings there to pin to The Graph's endpoint as well: …
> [smolverse] various fixes for smolverse prod deploy

- subgraphs/smolverse/schema.graphql
- subgraphs/smolverse/src/helpers/constants.ts
- subgraphs/smolverse/src/helpers/metadata.ts
- subgraphs/smolverse/src/helpers/models.ts
- subgraphs/smolverse/src/mappings/common.ts
- subgraphs/smolverse/src/mappings/smol-bodies.ts
- subgraphs/smolverse/src/mappings/smol-brains-land.ts
- subgraphs/smolverse/src/mappings/smol-brains.ts
- subgraphs/smolverse/src/mappings/smol-pets.ts
- subgraphs/smolverse/tests/helpers/metadata.test.ts
Closes #81 
Adds a cron job run on at least a one-hour interval on token transfer to check for any tokens that are missing metadata due to an `ipfs.cat` error and retries them.
> add cron job to handle failed IPFS pulls every hour

- subgraphs/bridgeworld-stats/matchstick.yaml
- subgraphs/bridgeworld-stats/package.json
- subgraphs/bridgeworld/matchstick.yaml
- subgraphs/bridgeworld/package.json
- subgraphs/marketplace/matchstick.yaml
- subgraphs/marketplace/package.json
- subgraphs/smolverse/matchstick.yaml
- subgraphs/smolverse/package.json
Fixes `graph test` command since the latest version of Matchstick dropped the `--lib` command in favor of a `matchstick.yaml` config file
> add matstick.yaml config for latest framework version

- packages/constants/src/index.template.ts
- subgraphs/bridgeworld-stats/schema.graphql
- subgraphs/bridgeworld-stats/src/helpers/constants.ts
- subgraphs/bridgeworld-stats/src/helpers/ids.ts
- subgraphs/bridgeworld-stats/src/helpers/models.ts
- subgraphs/bridgeworld-stats/src/mappings/crafting.ts
- subgraphs/bridgeworld-stats/src/mappings/questing.ts
- subgraphs/bridgeworld-stats/template.yaml
- subgraphs/bridgeworld-stats/tests/crafting/crafting.test.ts
- subgraphs/bridgeworld-stats/tests/crafting/utils.ts
- subgraphs/bridgeworld-stats/tests/questing/questing.test.ts
- subgraphs/bridgeworld-stats/tests/questing/utils.ts
- subgraphs/bridgeworld-stats/tests/utils.ts
Closes #36 
- Adds handlers for questing started, revealed, and finished along with stats for counting earnings per difficulty and legion type
- Fixes crafting stats bug recording treasure ID 0
> Add Questing stats

- packages/config/src/arbitrum-testnet.json
- packages/config/src/arbitrum.json
- packages/constants/src/index.template.ts
- subgraphs/bridgeworld-stats/src/helpers/models.ts
- subgraphs/bridgeworld-stats/src/mappings/atlas-mine.ts
- subgraphs/bridgeworld-stats/src/mappings/crafting.ts
- subgraphs/bridgeworld-stats/src/mappings/questing.ts
- subgraphs/bridgeworld-stats/src/mappings/summoning.ts
- subgraphs/bridgeworld-stats/tests/atlas-mine/utils.ts
- subgraphs/bridgeworld-stats/tests/crafting/utils.ts
- subgraphs/bridgeworld-stats/tests/questing/utils.ts
- subgraphs/bridgeworld-stats/tests/summoning/utils.ts
Some attempts at speeding up the sync times:
- Updates the hourly stats to only get created if we're syncing past the specific start block number. The Graph doesn't support `Date.now()` so we have to go by block time. Right now this start block is from ~7 days ago. We can periodically update the config when we make changes to the stats
- Reduces the amount of entity save calls in the model stats generator functions
> [bridgeworld-stats] filter hourly stats by block number; optimize stats models

- subgraphs/bridgeworld-stats/schema.graphql
- subgraphs/bridgeworld-stats/src/helpers/models.ts
- subgraphs/bridgeworld-stats/src/mappings/atlas-mine.ts
- subgraphs/bridgeworld-stats/src/mappings/crafting.ts
- subgraphs/bridgeworld-stats/src/mappings/questing.ts
- subgraphs/bridgeworld-stats/src/mappings/summoning.ts
- subgraphs/bridgeworld-stats/tests/atlas-mine/atlas-mine.test.ts
- subgraphs/bridgeworld-stats/tests/crafting/crafting.test.ts
- subgraphs/bridgeworld-stats/tests/questing/questing.test.ts
- subgraphs/bridgeworld-stats/tests/summoning/summoning.test.ts
- subgraphs/bridgeworld-stats/tests/utils.ts
Refactors the way we're logging user-based stats to avoid storing large arrays of addresses. Also gives the added benefit of having user stats per time interval.
> [bridgeworld-stats] refactor user stats to avoid address arrays

- subgraphs/bridgeworld-stats/template.yaml
Fixes the `bridgeworld-stats` syncing error by removing the unused/unmapped event handler for `NoPilgrimagesToFinish`
```
Subgraph failed with non-deterministic error: failed to process trigger: block #5043950 (0x3e88…1270), transaction 8c0fbc5a1a3724c2981f4402970bc3c18a63a79210e1696d2a0adc8e0e3e663a: function handleNoPilgrimagesToFinish not found, retry_delay_s: 1800, attempt: 5
```
> [bridgeworld-stats] remove unused event handler

- subgraphs/bridgeworld-stats/schema.graphql
- subgraphs/bridgeworld-stats/src/helpers/constants.ts
- subgraphs/bridgeworld-stats/src/helpers/models.ts
- subgraphs/bridgeworld-stats/src/mappings/pilgrimage.ts
- subgraphs/bridgeworld-stats/tests/helpers/models.test.ts
- Fixes #97 
- Fixes the subgraph sync error:
```
Subgraph failed with non-deterministic error: Error while processing block stream for a subgraph: store error: invalid input value for enum sgd238069.legion_class: "All-Class", retry_delay_s: 1800, attempt: 14
```
> [bridgeworld-stats] fix all-class legion class enum

- .github/workflows/deploy.yaml
- package.json
- subgraphs/bridgeworld-stats/package.json
- subgraphs/bridgeworld-stats/src/mappings/pilgrimage.ts
- subgraphs/bridgeworld-stats/tests/pilgrimage/pilgrimage.test.ts
- yarn.lock
- Updates packages
- Attempts to fix an issue seen in the Pilgrimage stats with some count clean-up
@wyze any other reason you can see for this mismatch?
```
{
"data": {
"pilgrimageStat": {
"pilgrimagesStarted": 4359,
"pilgrimagesFinished": 4397,
"activeAddressesCount": 19,
"allAddressesCount": 1680
}
}
}
```
Finished count is somehow more than started count in the synced production subgraph 🤔
> [bridgeworld-stats] attempt to fix pilgrimage stat counts

- subgraphs/bridgeworld-stats/package.json
- subgraphs/marketplace/package.json
- subgraphs/smolverse/package.json
Fixes unit tests by forcing a few subgraphs to use Matchstick v0.4.2. I believe there's a bug in v0.4.3 that fails on non-required `derivedFrom` relations, but haven't dug deeper into it yet
> fix unit tests by forcing matchstick 0.4.2

- .github/workflows/deploy.yaml
- packages/abis/src/SeedEvolution.json
- subgraphs/seed-of-life-stats/matchstick.yaml
- subgraphs/seed-of-life-stats/package.json
- subgraphs/seed-of-life-stats/schema.graphql
- subgraphs/seed-of-life-stats/src/helpers/constants.ts
- subgraphs/seed-of-life-stats/src/helpers/lifeform.ts
- subgraphs/seed-of-life-stats/src/helpers/number.ts
- subgraphs/seed-of-life-stats/src/helpers/path.ts
- subgraphs/seed-of-life-stats/src/helpers/random.ts
- subgraphs/seed-of-life-stats/src/helpers/realm.ts
- subgraphs/seed-of-life-stats/src/helpers/stat.ts
- subgraphs/seed-of-life-stats/src/helpers/treasure.ts
- subgraphs/seed-of-life-stats/src/mappings/randomizer.ts
- subgraphs/seed-of-life-stats/src/mappings/seed-evolution.ts
- subgraphs/seed-of-life-stats/template.yaml
- subgraphs/seed-of-life-stats/tests/seed-evolution/seed-evolution.test.ts
- subgraphs/seed-of-life-stats/tests/seed-evolution/utils.ts
- subgraphs/seed-of-life-stats/tests/utils.ts
- subgraphs/seed-of-life/src/mappings/seed-evolution.ts
We've discovered a mismatch in the ABI and contract code for Seed of Life Evolution:
ABI params say broken treasures: [https://github.com/TreasureProject/sol-contracts/blob/a081cd307386e6e1f5c4d8ed947b[…]f14a8/contracts/seedoflife/seedevolution/SeedEvolutionState.sol](https://github.com/TreasureProject/sol-contracts/blob/a081cd307386e6e1f5c4d8ed947b8339fcef14a8/contracts/seedoflife/seedevolution/SeedEvolutionState.sol#L24)
Event passes unstaking treasures: https://github.com/TreasureProject/sol-contracts/blob/main/contracts/seedoflife/seedevolution/SeedEvolution.sol#L293
I've updated the ABI in the subgraph repo to reflect the `_unstakingTreasureIds` that actually get passed into this function and refactored the processing of broken tokens
Added new Seed of Life Stats subgraph, already …
> Add Seed of Life Stats subgraph; fix broken token parsing on Seed of Life subgraph

- subgraphs/bridgeworld/src/mappings/legion.ts
- subgraphs/bridgeworld/tests/legion.test.ts
Fixes #117 
- Fills `generation` field for `Token` entities of category `Legion`
> fix token generation field for legions

- subgraphs/seed-of-life-stats/schema.graphql
- subgraphs/seed-of-life-stats/src/helpers/stat.ts
- subgraphs/seed-of-life-stats/src/mappings/seed-evolution.ts
- Adds new RealmComboStat entity to track stats for combinations of first and second realm
> [seed-of-life-stats] add realm combo stats

- subgraphs/metadata/src/helpers/json.ts
- subgraphs/metadata/src/mapping.ts
- subgraphs/metadata/src/mappings/lost-donkeys.ts
Forces a refresh on all Lost Donkeys metadata after block 12575754, a transfer event close to when the team launched the metadata changes.
> [metadata] force refresh Lost Donkeys metadata

- subgraphs/bridgeworld/src/mappings/advanced-questing.ts
Fixes issue with empty questing rewards still creating new entities in subgraph. There are a lot of empty entities that don't need to exist because the original `for` loop is creating and saving an entity on every iteration, not just the ones with actual rewards
https://thegraph.com/hosted-service/subgraph/treasureproject/bridgeworld
```
{
advancedQuestRewards(
where: {
consumable: null,
treasureFragment: null,
treasure: null
}
) {
id
}
}
```
> [bridgeworld] fix empty AdvancedQuestReward entities getting created

- subgraphs/bridgeworld/src/mappings/randomizer.ts
Updates the `hadStasisPartX` flags to track stasis hits when auto-progressing to the third part of a quest
> [bridgeworld] track stasis hits when auto-progressing

- subgraphs/bridgeworld/src/mappings/advanced-questing.ts
Adds condition to the new `endTime` recalculation so it only occurs if the Triad play resulted in some corrupted cards leftover
> only recalculate end time if triad results in stasis

- subgraphs/bridgeworld/schema.graphql
- subgraphs/bridgeworld/src/mappings/mini-crafting.ts
Adds `blockNumber` field to the `MiniCraft` entity so we can group batches of mini crafts on the front-end. `timestamp` is not unique per batch because Arbitrum applies the L1 block timestamp to the transaction, and multiple blocks/batches can have the same exact timestamp
> add block number to mini craft because timestamp is not unique per group

- packages/abis/src/AdvancedQuesting.json
- packages/abis/src/Questing.json
- subgraphs/bridgeworld/schema.graphql
- subgraphs/bridgeworld/src/helpers/config.ts
- subgraphs/bridgeworld/src/helpers/legion.ts
- subgraphs/bridgeworld/src/mappings/advanced-questing.ts
- subgraphs/bridgeworld/src/mappings/legion.ts
- subgraphs/bridgeworld/src/mappings/questing.ts
- subgraphs/bridgeworld/template.yaml
- subgraphs/bridgeworld/tests/advanced-questing.test.ts
- subgraphs/bridgeworld/tests/helpers/advanced-questing.ts
- subgraphs/bridgeworld/tests/helpers/legion.ts
- subgraphs/bridgeworld/tests/helpers/questing.ts
- subgraphs/bridgeworld/tests/legion.test.ts
- subgraphs/bridgeworld/tests/questing.test.ts
- Adds new handlers for Questing XP gained events
- Adds checks to skip old Questing XP calculations after upgrade block number
Deployed to testnet: https://thegraph.com/hosted-service/subgraph/treasureproject/bridgeworld-dev
> add handlers for new questing xp gained events

- subgraphs/bridgeworld/schema.graphql
- subgraphs/bridgeworld/src/helpers/constants.ts
- subgraphs/bridgeworld/src/mappings/advanced-questing.ts
- subgraphs/bridgeworld/src/mappings/crafting.ts
- subgraphs/bridgeworld/src/mappings/mini-crafting.ts
- subgraphs/bridgeworld/src/mappings/questing.ts
- subgraphs/bridgeworld/tests/advanced-questing.test.ts
- subgraphs/bridgeworld/tests/crafting.test.ts
- subgraphs/bridgeworld/tests/helpers/advanced-questing.ts
- subgraphs/bridgeworld/tests/mini-crafting.test.ts
- subgraphs/bridgeworld/tests/questing.test.ts
Adds new fields to the `LegionInfo` entity for tracking quest and craft counts plus a new "distance travelled" concept
> add quest and craft counts to legion metadata

- subgraphs/smolverse/src/mappings/smol-brains.ts
- subgraphs/smolverse/template.yaml
- Defaults to hard-coded base URI if the contract call returns an empty string
- Queues up all Smol Brains tokens for metadata refetching when base URI changes
> refetch collection metadata when base uri changes

- package.json
- subgraphs/bridgeworld-approvals/package.json
- subgraphs/bridgeworld-approvals/schema.graphql
- subgraphs/bridgeworld-approvals/src/mapping.ts
- subgraphs/bridgeworld-approvals/tests/approval.test.ts
- subgraphs/bridgeworld/package.json
- subgraphs/bridgeworld/src/helpers/summoning-circle.ts
- subgraphs/bridgeworld/src/mapping.ts
- subgraphs/bridgeworld/src/mappings/atlas-mine.ts
- subgraphs/bridgeworld/src/mappings/legion.ts
- subgraphs/bridgeworld/src/mappings/magic.ts
- subgraphs/bridgeworld/src/mappings/summoning.ts
- subgraphs/magic-stats/package.json
- subgraphs/magic-stats/src/helpers/models.ts
- subgraphs/migration/schema.graphql
- subgraphs/migration/src/mapping.ts
- subgraphs/smol-racing/package.json
- subgraphs/smolverse/package.json
- subgraphs/smolverse/src/helpers/models.ts
- yarn.lock
Using `immutable: true` in the entities, as well as `Bytes` for the ids should speed up syncing and querying times.
https://thegraph.com/docs/en/developing/creating-a-subgraph/#defining-entities
> Immutable entities are much faster to write and to query, and should therefore be used whenever possible.
> It is generally recommended to use `Bytes!`, unless the `id` contains human-readable text, since entities with `Bytes!` id's will be faster to write and query as those with a `String!` `id`.
Additionally update the `@graphprotocol/*` dependencies as well as the tests to pass with the new versions.
> Update bridgeworld-approvals to use immutable entities
